# Nginx Module Setting
filebeat.modules:
- module: nginx

  # Access logs
  access:
    enabled: true
    var.paths: ["/data/nginx/logs/access.log"]

  # Error logs
  error:
    enabled: true
    var.paths: ["/data/nginx/logs/error.log"]

# Elasticsearch template setting
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

# Kibana setting
setup.kibana:
  host: "0.0.0.0:5601"

# Elasticsearch output
output.elasticsearch:
  hosts: "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"

# Processors
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
